version: "2"
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    network_mode: host
  sixpack_server:
    image: ariepratama/sixpack-docker:latest
    depends_on:
      - redis
    ports:
      - "5000:5000"
    command: "sixpack"
    network_mode: host
  sixpack_web:
    image: ariepratama/sixpack-docker:latest
    depends_on:
      - redis
    ports:
      - "5001:5001"
    command: "sixpack-web"
    network_mode: host